<a href="https://colab.research.google.com/github/atif4/Q2/blob/gh-pages/iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
#hide earrings 
import warnings
warnings.filterwarnings('ignore')

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam, SGD
#from tensorflow.keras.utils import to_categorical

In [3]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [4]:
df = pd.read_csv('/content/drive/MyDrive/Dataset/iris.csv')
df.drop('Unnamed: 0', axis=1, inplace=True)

In [5]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
print(f"{df.info()}\n{df.shape}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None
(150, 5)

In [7]:
def get_seprate_features(df_id,col_id):
    #col_id is special col or target col b/c this the whole model is going to be created 
    global X, y
    X = df_id.drop(col_id,axis = 1) 
    y = df_id[col_id]
get_seprate_features(df,['species'])

In [8]:
X

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [9]:
min_max_scaler = preprocessing.MinMaxScaler()
X = min_max_scaler.fit_transform(X)
X

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     , 0.06779661, 0.08333333],
       [0.38888889, 0.75      , 0.11864407, 0.08333333],
       [0.22222222, 0.75      , 0.08474576, 0.08333333],
       [0.30555556, 0.58333333, 0.11864407, 0.04166667],
       [0.22222222, 0.70833333, 0.08474576, 0.125     ],
       [0.08333333, 0.66666667, 0.        , 0.04166667],
       [0.22222222, 0.54166667, 0.11864407, 0.16666667],
       [0.13888889, 0.58333333, 0.15254237, 0.04166667],
       [0.19444444, 0.41666667, 0.10169492, 0.04166667],
       [0.19444444, 0.58333333, 0.10169492, 0.125     ],
       [0.25      , 0.625     , 0.08474576, 0.04166667],
       [0.25      , 0.58333333, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.10169492, 0.04166667],
       [0.13888889, 0.45833333, 0.10169492, 0.04166667],
       [0.30555556, 0.58333333, 0.08474576, 0.125     ],
       [0.25      , 0.875     , 0.08474576, 0.        ],
       [0.33333333, 0.91666667, 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.5       , 0.03389831, 0.04166667],
       [0.33333333, 0.625     , 0.05084746, 0.04166667],
       [0.16666667, 0.66666667, 0.06779661, 0.        ],
       [0.02777778, 0.41666667, 0.05084746, 0.04166667],
       [0.22222222, 0.58333333, 0.08474576, 0.04166667],
       [0.19444444, 0.625     , 0.05084746, 0.08333333],
       [0.05555556, 0.125     , 0.05084746, 0.08333333],
       [0.02777778, 0.5       , 0.05084746, 0.04166667],
       [0.19444444, 0.625     , 0.10169492, 0.20833333],
       [0.22222222, 0.75      , 0.15254237, 0.125     ],
       [0.13888889, 0.41666667, 0.06779661, 0.08333333],
       [0.22222222, 0.75      , 0.10169492, 0.04166667],
       [0.08333333, 0.5       , 0.06779661, 0.04166667],
       [0.27777778, 0.70833333, 0.08474576, 0.04166667],
       [0.19444444, 0.54166667, 0.06779661, 0.04166667],
       [0.75      , 0.5       , 0.62711864, 0.54166667],
       [0.58333333, 0.5       , 0.59322034, 0.58333333],
       [0.72222222, 0.45833333, 0.66101695, 0.58333333],
       [0.33333333, 0.125     , 0.50847458, 0.5       ],
       [0.61111111, 0.33333333, 0.61016949, 0.58333333],
       [0.38888889, 0.33333333, 0.59322034, 0.5       ],
       [0.55555556, 0.54166667, 0.62711864, 0.625     ],
       [0.16666667, 0.16666667, 0.38983051, 0.375     ],
       [0.63888889, 0.375     , 0.61016949, 0.5       ],
       [0.25      , 0.29166667, 0.49152542, 0.54166667],
       [0.19444444, 0.        , 0.42372881, 0.375     ],
       [0.44444444, 0.41666667, 0.54237288, 0.58333333],
       [0.47222222, 0.08333333, 0.50847458, 0.375     ],
       [0.5       , 0.375     , 0.62711864, 0.54166667],
       [0.36111111, 0.375     , 0.44067797, 0.5       ],
       [0.66666667, 0.45833333, 0.57627119, 0.54166667],
       [0.36111111, 0.41666667, 0.59322034, 0.58333333],
       [0.41666667, 0.29166667, 0.52542373, 0.375     ],
       [0.52777778, 0.08333333, 0.59322034, 0.58333333],
       [0.36111111, 0.20833333, 0.49152542, 0.41666667],
       [0.44444444, 0.5       , 0.6440678 , 0.70833333],
       [0.5       , 0.33333333, 0.50847458, 0.5       ],
       [0.55555556, 0.20833333, 0.66101695, 0.58333333],
       [0.5       , 0.33333333, 0.62711864, 0.45833333],
       [0.58333333, 0.375     , 0.55932203, 0.5       ],
       [0.63888889, 0.41666667, 0.57627119, 0.54166667],
       [0.69444444, 0.33333333, 0.6440678 , 0.54166667],
       [0.66666667, 0.41666667, 0.6779661 , 0.66666667],
       [0.47222222, 0.375     , 0.59322034, 0.58333333],
       [0.38888889, 0.25      , 0.42372881, 0.375     ],
       [0.33333333, 0.16666667, 0.47457627, 0.41666667],
       [0.33333333, 0.16666667, 0.45762712, 0.375     ],
       [0.41666667, 0.29166667, 0.49152542, 0.45833333],
       [0.47222222, 0.29166667, 0.69491525, 0.625     ],
       [0.30555556, 0.41666667, 0.59322034, 0.58333333],
       [0.47222222, 0.58333333, 0.59322034, 0.625     ],
       [0.66666667, 0.45833333, 0.62711864, 0.58333333],
       [0.55555556, 0.125     , 0.57627119, 0.5       ],
       [0.36111111, 0.41666667, 0.52542373, 0.5       ],
       [0.33333333, 0.20833333, 0.50847458, 0.5       ],
       [0.33333333, 0.25      , 0.57627119, 0.45833333],
       [0.5       , 0.41666667, 0.61016949, 0.54166667],
       [0.41666667, 0.25      , 0.50847458, 0.45833333],
       [0.19444444, 0.125     , 0.38983051, 0.375     ],
       [0.36111111, 0.29166667, 0.54237288, 0.5       ],
       [0.38888889, 0.41666667, 0.54237288, 0.45833333],
       [0.38888889, 0.375     , 0.54237288, 0.5       ],
       [0.52777778, 0.375     , 0.55932203, 0.5       ],
       [0.22222222, 0.20833333, 0.33898305, 0.41666667],
       [0.38888889, 0.33333333, 0.52542373, 0.5       ],
       [0.55555556, 0.54166667, 0.84745763, 1.        ],
       [0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.77777778, 0.41666667, 0.83050847, 0.83333333],
       [0.55555556, 0.375     , 0.77966102, 0.70833333],
       [0.61111111, 0.41666667, 0.81355932, 0.875     ],
       [0.91666667, 0.41666667, 0.94915254, 0.83333333],
       [0.16666667, 0.20833333, 0.59322034, 0.66666667],
       [0.83333333, 0.375     , 0.89830508, 0.70833333],
       [0.66666667, 0.20833333, 0.81355932, 0.70833333],
       [0.80555556, 0.66666667, 0.86440678, 1.        ],
       [0.61111111, 0.5       , 0.69491525, 0.79166667],
       [0.58333333, 0.29166667, 0.72881356, 0.75      ],
       [0.69444444, 0.41666667, 0.76271186, 0.83333333],
       [0.38888889, 0.20833333, 0.6779661 , 0.79166667],
       [0.41666667, 0.33333333, 0.69491525, 0.95833333],
       [0.58333333, 0.5       , 0.72881356, 0.91666667],
       [0.61111111, 0.41666667, 0.76271186, 0.70833333],
       [0.94444444, 0.75      , 0.96610169, 0.875     ],
       [0.94444444, 0.25      , 1.        , 0.91666667],
       [0.47222222, 0.08333333, 0.6779661 , 0.58333333],
       [0.72222222, 0.5       , 0.79661017, 0.91666667],
       [0.36111111, 0.33333333, 0.66101695, 0.79166667],
       [0.94444444, 0.33333333, 0.96610169, 0.79166667],
       [0.55555556, 0.29166667, 0.66101695, 0.70833333],
       [0.66666667, 0.54166667, 0.79661017, 0.83333333],
       [0.80555556, 0.5       , 0.84745763, 0.70833333],
       [0.52777778, 0.33333333, 0.6440678 , 0.70833333],
       [0.5       , 0.41666667, 0.66101695, 0.70833333],
       [0.58333333, 0.33333333, 0.77966102, 0.83333333],
       [0.80555556, 0.41666667, 0.81355932, 0.625     ],
       [0.86111111, 0.33333333, 0.86440678, 0.75      ],
       [1.        , 0.75      , 0.91525424, 0.79166667],
       [0.58333333, 0.33333333, 0.77966102, 0.875     ],
       [0.55555556, 0.33333333, 0.69491525, 0.58333333],
       [0.5       , 0.25      , 0.77966102, 0.54166667],
       [0.94444444, 0.41666667, 0.86440678, 0.91666667],
       [0.55555556, 0.58333333, 0.77966102, 0.95833333],
       [0.58333333, 0.45833333, 0.76271186, 0.70833333],
       [0.47222222, 0.41666667, 0.6440678 , 0.70833333],
       [0.72222222, 0.45833333, 0.74576271, 0.83333333],
       [0.66666667, 0.45833333, 0.77966102, 0.95833333],
       [0.72222222, 0.45833333, 0.69491525, 0.91666667],
       [0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.69444444, 0.5       , 0.83050847, 0.91666667],
       [0.66666667, 0.54166667, 0.79661017, 1.        ],
       [0.66666667, 0.41666667, 0.71186441, 0.91666667],
       [0.55555556, 0.20833333, 0.6779661 , 0.75      ],
       [0.61111111, 0.41666667, 0.71186441, 0.79166667],
       [0.52777778, 0.58333333, 0.74576271, 0.91666667],
       [0.44444444, 0.41666667, 0.69491525, 0.70833333]])

In [10]:
y

       species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]

In [11]:
y.shape

(150, 1)

In [12]:
encoder =  LabelEncoder()
y = encoder.fit_transform(y)
y.shape

(150,)

In [13]:
y = pd.get_dummies(y)#.values

In [14]:
y

     0  1  2
0    1  0  0
1    1  0  0
2    1  0  0
3    1  0  0
4    1  0  0
..  .. .. ..
145  0  0  1
146  0  0  1
147  0  0  1
148  0  0  1
149  0  0  1

[150 rows x 3 columns]

In [15]:
def get_train_test_split(array1, array2, test_size, random_state):
    global X_train, X_test, y_train, y_test
    X_train, X_test, y_train, y_test = train_test_split(array1, array2, test_size=test_size,random_state=random_state)
get_train_test_split(X,y,0.3,1)

In [16]:
print(f'X_train: {X_train.shape} y_train: {y_train.shape}  \nX_test: {X_test.shape} y_test: {y_test.shape}')

X_train: (105, 4) y_train: (105, 3)
X_test: (45, 4) y_test: (45, 3)

In [17]:
model = Sequential()
model.add(Dense(32, activation='relu', input_shape=(4,)))
model.add(Dense(24, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [18]:
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

In [19]:
model.fit(X_train, y_train, batch_size=50, epochs=100)

Epoch 1/100
3/3 [==============================] - 0s 5ms/step - loss: 1.0691 - accuracy: 0.4095
Epoch 2/100
3/3 [==============================] - 0s 3ms/step - loss: 1.0481 - accuracy: 0.5619
Epoch 3/100
3/3 [==============================] - 0s 3ms/step - loss: 1.0381 - accuracy: 0.5333
Epoch 4/100
3/3 [==============================] - 0s 4ms/step - loss: 1.0289 - accuracy: 0.5429
Epoch 5/100
3/3 [==============================] - 0s 3ms/step - loss: 1.0204 - accuracy: 0.6667
Epoch 6/100
3/3 [==============================] - 0s 6ms/step - loss: 1.0116 - accuracy: 0.6286
Epoch 7/100
3/3 [==============================] - 0s 4ms/step - loss: 1.0027 - accuracy: 0.6476
Epoch 8/100
3/3 [==============================] - 0s 7ms/step - loss: 0.9951 - accuracy: 0.6381
Epoch 9/100
3/3 [==============================] - 0s 4ms/step - loss: 0.9865 - accuracy: 0.6571
Epoch 10/100
3/3 [==============================] - 0s 4ms/step - loss: 0.9751 - accuracy: 0.6667
Epoch 11/100
3/3 [==============================] - 0s 3ms/step - loss: 0.9626 - accuracy: 0.6952
Epoch 12/100
3/3 [==============================] - 0s 3ms/step - loss: 0.9522 - accuracy: 0.6952
Epoch 13/100
3/3 [==============================] - 0s 3ms/step - loss: 0.9417 - accuracy: 0.6952
Epoch 14/100
3/3 [==============================] - 0s 4ms/step - loss: 0.9292 - accuracy: 0.6952
Epoch 15/100
3/3 [==============================] - 0s 6ms/step - loss: 0.9170 - accuracy: 0.6952
Epoch 16/100
3/3 [==============================] - 0s 3ms/step - loss: 0.9058 - accuracy: 0.6952
Epoch 17/100
3/3 [==============================] - 0s 3ms/step - loss: 0.8948 - accuracy: 0.6952
Epoch 18/100
3/3 [==============================] - 0s 4ms/step - loss: 0.8835 - accuracy: 0.6952
Epoch 19/100
3/3 [==============================] - 0s 4ms/step - loss: 0.8727 - accuracy: 0.6952
Epoch 20/100
3/3 [==============================] - 0s 4ms/step - loss: 0.8601 - accuracy: 0.6952
Epoch 21/100
3/3 [==============================] - 0s 3ms/step - loss: 0.8506 - accuracy: 0.6952
Epoch 22/100
3/3 [==============================] - 0s 3ms/step - loss: 0.8400 - accuracy: 0.6952
Epoch 23/100
3/3 [==============================] - 0s 4ms/step - loss: 0.8302 - accuracy: 0.6952
Epoch 24/100
3/3 [==============================] - 0s 4ms/step - loss: 0.8203 - accuracy: 0.6952
Epoch 25/100
3/3 [==============================] - 0s 4ms/step - loss: 0.8123 - accuracy: 0.6952
Epoch 26/100
3/3 [==============================] - 0s 4ms/step - loss: 0.8022 - accuracy: 0.6952
Epoch 27/100
3/3 [==============================] - 0s 6ms/step - loss: 0.7924 - accuracy: 0.6952
Epoch 28/100
3/3 [==============================] - 0s 4ms/step - loss: 0.7821 - accuracy: 0.6952
Epoch 29/100
3/3 [==============================] - 0s 4ms/step - loss: 0.7703 - accuracy: 0.6952
Epoch 30/100
3/3 [==============================] - 0s 4ms/step - loss: 0.7610 - accuracy: 0.6952
Epoch 31/100
3/3 [==============================] - 0s 3ms/step - loss: 0.7488 - accuracy: 0.6952
Epoch 32/100
3/3 [==============================] - 0s 4ms/step - loss: 0.7384 - accuracy: 0.6952
Epoch 33/100
3/3 [==============================] - 0s 3ms/step - loss: 0.7266 - accuracy: 0.6952
Epoch 34/100
3/3 [==============================] - 0s 3ms/step - loss: 0.7156 - accuracy: 0.6952
Epoch 35/100
3/3 [==============================] - 0s 4ms/step - loss: 0.7043 - accuracy: 0.6952
Epoch 36/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6935 - accuracy: 0.6952
Epoch 37/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6824 - accuracy: 0.6952
Epoch 38/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6720 - accuracy: 0.6952
Epoch 39/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6633 - accuracy: 0.6952
Epoch 40/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6548 - accuracy: 0.6952
Epoch 41/100
3/3 [==============================] - 0s 3ms/step - loss: 0.6432 - accuracy: 0.6952
Epoch 42/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6334 - accuracy: 0.6952
Epoch 43/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6234 - accuracy: 0.6952
Epoch 44/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6125 - accuracy: 0.6952
Epoch 45/100
3/3 [==============================] - 0s 4ms/step - loss: 0.6037 - accuracy: 0.6952
Epoch 46/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5958 - accuracy: 0.6952
Epoch 47/100
3/3 [==============================] - 0s 5ms/step - loss: 0.5863 - accuracy: 0.6952
Epoch 48/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5792 - accuracy: 0.6952
Epoch 49/100
3/3 [==============================] - 0s 8ms/step - loss: 0.5704 - accuracy: 0.6952
Epoch 50/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5616 - accuracy: 0.6952
Epoch 51/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5548 - accuracy: 0.6952
Epoch 52/100
3/3 [==============================] - 0s 3ms/step - loss: 0.5479 - accuracy: 0.6952
Epoch 53/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5402 - accuracy: 0.6952
Epoch 54/100
3/3 [==============================] - 0s 3ms/step - loss: 0.5337 - accuracy: 0.6952
Epoch 55/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5291 - accuracy: 0.6952
Epoch 56/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5236 - accuracy: 0.6952
Epoch 57/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5192 - accuracy: 0.6952
Epoch 58/100
3/3 [==============================] - 0s 3ms/step - loss: 0.5137 - accuracy: 0.6952
Epoch 59/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5093 - accuracy: 0.6952
Epoch 60/100
3/3 [==============================] - 0s 3ms/step - loss: 0.5026 - accuracy: 0.6952
Epoch 61/100
3/3 [==============================] - 0s 4ms/step - loss: 0.4950 - accuracy: 0.6952
Epoch 62/100
3/3 [==============================] - 0s 5ms/step - loss: 0.4889 - accuracy: 0.6952
Epoch 63/100
3/3 [==============================] - 0s 4ms/step - loss: 0.4836 - accuracy: 0.6952
Epoch 64/100
3/3 [==============================] - 0s 4ms/step - loss: 0.4811 - accuracy: 0.6952
Epoch 65/100
3/3 [==============================] - 0s 5ms/step - loss: 0.4749 - accuracy: 0.6952
Epoch 66/100
3/3 [==============================] - 0s 3ms/step - loss: 0.4698 - accuracy: 0.6952
Epoch 67/100
3/3 [==============================] - 0s 3ms/step - loss: 0.4668 - accuracy: 0.6952
Epoch 68/100
3/3 [==============================] - 0s 3ms/step - loss: 0.4610 - accuracy: 0.6952
Epoch 69/100
3/3 [==============================] - 0s 4ms/step - loss: 0.4565 - accuracy: 0.6952
Epoch 70/100
3/3 [==============================] - 0s 4ms/step - loss: 0.4543 - accuracy: 0.6952
Epoch 71/100
3/3 [==============================] - 0s 5ms/step - loss: 0.4508 - accuracy: 0.6952
Epoch 72/100
3/3 [==============================] - 0s 5ms/step - loss: 0.4459 - accuracy: 0.7333
Epoch 73/100
3/3 [==============================] - 0s 5ms/step - loss: 0.4430 - accuracy: 0.7143
Epoch 74/100
3/3 [==============================] - 0s 4ms/step - loss: 0.4402 - accuracy: 0.7143
Epoch 75/100
3/3 [==============================] - 0s 5ms/step - loss: 0.4391 - accuracy: 0.7619
Epoch 76/100
3/3 [==============================] - 0s 5ms/step - loss: 0.4354 - accuracy: 0.8000
Epoch 77/100
3/3 [==============================] - 0s 4ms/step - loss: 0.4328 - accuracy: 0.8095
Epoch 78/100
3/3 [==============================] - 0s 4ms/step - loss: 0.4276 - accuracy: 0.7524
Epoch 79/100
3/3 [==============================] - 0s 4ms/step - loss: 0.4240 - accuracy: 0.7524
Epoch 80/100
3/3 [==============================] - 0s 4ms/step - loss: 0.4225 - accuracy: 0.7143
Epoch 81/100
3/3 [==============================] - 0s 4ms/step - loss: 0.4192 - accuracy: 0.7524
Epoch 82/100
3/3 [==============================] - 0s 4ms/step - loss: 0.4153 - accuracy: 0.7524
Epoch 83/100
3/3 [==============================] - 0s 4ms/step - loss: 0.4135 - accuracy: 0.8286
Epoch 84/100
3/3 [==============================] - 0s 4ms/step - loss: 0.4104 - accuracy: 0.8190
Epoch 85/100
3/3 [==============================] - 0s 3ms/step - loss: 0.4074 - accuracy: 0.7524
Epoch 86/100
3/3 [==============================] - 0s 3ms/step - loss: 0.4071 - accuracy: 0.7333
Epoch 87/100
3/3 [==============================] - 0s 3ms/step - loss: 0.4040 - accuracy: 0.7333
Epoch 88/100
3/3 [==============================] - 0s 3ms/step - loss: 0.3997 - accuracy: 0.8476
Epoch 89/100
3/3 [==============================] - 0s 3ms/step - loss: 0.3972 - accuracy: 0.8857
Epoch 90/100
3/3 [==============================] - 0s 4ms/step - loss: 0.3943 - accuracy: 0.8667
Epoch 91/100
3/3 [==============================] - 0s 3ms/step - loss: 0.3915 - accuracy: 0.8857
Epoch 92/100
3/3 [==============================] - 0s 3ms/step - loss: 0.3899 - accuracy: 0.9143
Epoch 93/100
3/3 [==============================] - 0s 3ms/step - loss: 0.3901 - accuracy: 0.9524
Epoch 94/100
3/3 [==============================] - 0s 3ms/step - loss: 0.3838 - accuracy: 0.8857
Epoch 95/100
3/3 [==============================] - 0s 4ms/step - loss: 0.3819 - accuracy: 0.8381
Epoch 96/100
3/3 [==============================] - 0s 4ms/step - loss: 0.3802 - accuracy: 0.8381
Epoch 97/100
3/3 [==============================] - 0s 4ms/step - loss: 0.3787 - accuracy: 0.9143
Epoch 98/100
3/3 [==============================] - 0s 5ms/step - loss: 0.3768 - accuracy: 0.9143
Epoch 99/100
3/3 [==============================] - 0s 4ms/step - loss: 0.3747 - accuracy: 0.9143
Epoch 100/100
3/3 [==============================] - 0s 4ms/step - loss: 0.3716 - accuracy: 0.8667

In [20]:
test_loss, test_acc = model.evaluate(X_test, y_test) # evaluate -> estimate the significance

2/2 [==============================] - 0s 6ms/step - loss: 0.4087 - accuracy: 0.7556

In [21]:
print(f'Test accuracy:{test_acc*100}\nTest loss: {test_loss*100}')

Test accuracy:75.55555701255798
Test loss: 40.87071716785431

In [22]:
df1 = pd.DataFrame(np.random.rand(25,4), columns = ["sepal_length",	"sepal_width", "petal_length",	"petal_width"])
df1

    sepal_length  sepal_width  petal_length  petal_width
0       0.052497     0.571375      0.383335     0.511123
1       0.978499     0.033409      0.827895     0.399838
2       0.335883     0.508329      0.602308     0.740098
3       0.945126     0.231415      0.686911     0.633434
4       0.925350     0.852731      0.092013     0.875958
5       0.779371     0.237042      0.984303     0.651908
6       0.975057     0.842273      0.209413     0.850689
7       0.457538     0.710582      0.198893     0.994338
8       0.578943     0.077320      0.421036     0.833386
9       0.873131     0.338620      0.680370     0.760058
10      0.557594     0.406344      0.077210     0.846283
11      0.767567     0.082960      0.593661     0.249822
12      0.351432     0.328667      0.504946     0.578030
13      0.223545     0.240518      0.630349     0.075711
14      0.008267     0.755091      0.196314     0.676170
15      0.199638     0.793475      0.155022     0.539596
16      0.119307     0.049174      0.069172     0.832776
17      0.840033     0.659111      0.322800     0.814781
18      0.581521     0.929232      0.161860     0.857609
19      0.265169     0.181083      0.840947     0.482022
20      0.908600     0.651702      0.955908     0.271206
21      0.669475     0.675036      0.493089     0.690577
22      0.796513     0.410688      0.246184     0.130728
23      0.613204     0.339798      0.703922     0.272034
24      0.733053     0.124385      0.565398     0.421030

In [26]:
y_test.columns.take(np.argmax(model.predict([[0.4,	0.0,	0.5,	0.7]]), axis=1))
#Y.columns.take(np.argmax(model.predict([[90,90,59,70,95]]), axis=1))
#y_test.columns.take(np.argmax(model.predict(df1.loc[:,'sepal_length':'petal_width']), axis=1))

1/1 [==============================] - 0s 25ms/step

Int64Index([2], dtype='int64')

In [27]:
df1['predict'] = y_test.columns.take(np.argmax(model.predict(df1.loc[:,'sepal_length':'petal_width']), axis=1))
df1

1/1 [==============================] - 0s 46ms/step

    sepal_length  sepal_width  petal_length  petal_width  predict
0       0.052497     0.571375      0.383335     0.511123        0
1       0.978499     0.033409      0.827895     0.399838        2
2       0.335883     0.508329      0.602308     0.740098        2
3       0.945126     0.231415      0.686911     0.633434        2
4       0.925350     0.852731      0.092013     0.875958        0
5       0.779371     0.237042      0.984303     0.651908        2
6       0.975057     0.842273      0.209413     0.850689        1
7       0.457538     0.710582      0.198893     0.994338        0
8       0.578943     0.077320      0.421036     0.833386        2
9       0.873131     0.338620      0.680370     0.760058        2
10      0.557594     0.406344      0.077210     0.846283        1
11      0.767567     0.082960      0.593661     0.249822        1
12      0.351432     0.328667      0.504946     0.578030        1
13      0.223545     0.240518      0.630349     0.075711        1
14      0.008267     0.755091      0.196314     0.676170        0
15      0.199638     0.793475      0.155022     0.539596        0
16      0.119307     0.049174      0.069172     0.832776        1
17      0.840033     0.659111      0.322800     0.814781        1
18      0.581521     0.929232      0.161860     0.857609        0
19      0.265169     0.181083      0.840947     0.482022        2
20      0.908600     0.651702      0.955908     0.271206        2
21      0.669475     0.675036      0.493089     0.690577        1
22      0.796513     0.410688      0.246184     0.130728        1
23      0.613204     0.339798      0.703922     0.272034        1
24      0.733053     0.124385      0.565398     0.421030        2